name: Release Preview

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  release_preview:
    uses: OpenVoiceOS/gh-automations/.github/workflows/release-preview.yml@dev
    secrets: inherit
    with:
      package_name: 'ovos_a2a_solver'
      version_file: 'ovos_a2a_solver/version.py'
